service: notes-app-api
useDotenv: true

custom:
  stage: ${opt:stage, self:provider.stage}
  table: ${self:custom.stage}-notes

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs14.x
  stage: prod
  region: eu-north-1

  environment:
    tableName: ${self:custom.table}
    stripeSecretKey: ${env:STRIPE_SECRET_KEY}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: 
            Fn::GetAtt: [NotesTable, Arn]

functions:
  create:
    handler: lambdas/create.main
    events:
      - http:
          path: notes
          method: post
          cors: true
          authorizer: 
            type: aws_iam
  get:
    handler: lambdas/get.main
    events:
      - http:
          path: notes/{id}
          method: get
          cors: true
          authorizer: 
            type: aws_iam
  list:
    handler: lambdas/list.main
    events:
      - http:
          path: notes
          method: get
          cors: true
          authorizer: 
            type: aws_iam
  update:
    handler: lambdas/update.main
    events:
      - http:
          path: notes/{id}
          method: patch
          cors: true
          authorizer: 
            type: aws_iam
  delete:
    handler: lambdas/delete.main
    events:
      - http:
          path: notes/{id}
          method: delete
          cors: true
          authorizer: 
            type: aws_iam
  billing:
    handler: lambdas/billing.main
    events:
      - http:
          path: billing
          method: post
          cors: true
          authorizer: 
            type: aws_iam

resources:
  - ${file(resources/api-gateway-errors.yml)}
  - ${file(resources/dynamodb-table.yml)}
  - ${file(resources/s3-bucket.yml)}
  - ${file(resources/cognito-user-pool.yml)}
  - ${file(resources/cognito-identity-pool.yml)}

