Resources:
  AttachmentsBucket:
    Type: AWS::S3::Bucket
    Properties:
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: 
              - "*"
            AllowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - HEAD
            AllowedOrigins: 
              - "*"
            MaxAge: 3000

Outputs:
  AttachmentsBucketName:
    Value:
      Ref: AttachmentsBucket
